[package]
name = "jidoka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.7.1"
memmap2 = "0.5.2"
once_cell = "1.9.0"
rug = "1.15.0"
thiserror = "1.0.30"
